### PR TITLE
Simplified afterscripts

### LINKED ISSUE #35: Struggles with afterscripts
Hi,

I'm currently working with gourd and I tried to do some postprocessing, specifically through afterscripts (though I could rewrite it to use the postprocessing workflow, or next according to #32, but it seems that would require me to wait for the mentioned documentation).
Currently I've downgraded my script to be exactly what it says in the documentation:

gourd.toml:
```toml
[program.program_name]
binary = "/path/to/binary/pumpkin-cli"
arguments = ["several", "different", "flags"]
afterscript = "./script.sh"
```
script.sh:
```sh
echo $1 > $2
```

However, upon running, I (repeatedly) get the following error message:
```
warn: No output found for afterscript of run #1: caused by: Could not run the afterscript at "/full/correct/path/to/script.sh" with job results at "/full/correct/path/to/experiments/44/0/1/stdout"
 |
 |  help: Check that the afterscript is correct and job results exist at "/full/correct/path/to/experiments/44/0/1/stdout"
 |
 |  Check that the afterscript correctly places the output in a file.
```

What am I missing? Or, perhaps more precisely: is something missing in the documentation? Or did I simply read it wrong?

### PR DESCRIPTION
**Pull request by andtsa**
reworked after scripts so they just print (`echo`) their output to stdout, instead of a file. gourd collects the stdout and stores it in the experiment lockfile
benefits:
- the documentation is much simpler,
- less error prone as the user doesn't have to deal with any unnecessary files
- on the slow file system of delft blue, it means you are not creating thousands of files when you run `gourd status`

codebase changes:
- detached afterscript running from status gathering: status shouldn't modify the experiment, but running after scripts should. the after scripts are meant to have a short output, which can be efficiently stored in the already existing experiment lockfile. 
- `afterscript_output_path: Option<PathBuf>` of the `Run` struct is now `afterscript_output: Option<String>`

should resolve #35 

still todo:
- [x] document the need for shebangs
    - gourd.7 tutorial
    - gourd.5 toml
    - gourd.1
- [x] either add option or by default, display stdout and stderr of after scripts in gourd status
- [x] in documentation, explain how the argument is the job out file and the afterscript just needs to print stuff to stdout 
- [x] try slimming down new dependencies

- [x] figure out why pipeline tests fail (but pass locally)

### CODE REVIEW

File: src/gourd/wrapper/mod.rs [hunk 1]
```diff
@@ -51,7 +51,7 @@ pub fn wrap(
 
         verify_arch(&program.binary, arch, fs)?;
 
-        let mut cmd = Command::new(&experiment.wrapper);
+        let mut cmd = Command::new(shellexpand::full(&experiment.wrapper)?.to_string());
```
Comment (mgazeel) [inline src/gourd/wrapper/mod.rs:54]: Why are we evaluating POSIX shell? Why are we doing this? I really dislike this (a lot)

File: src/gourd_lib/config/mod.rs [hunk 2]
```diff
@@ -75,6 +74,31 @@ pub struct UserProgram {
     pub next: Vec<String>,
 }
 
+/// The user-facing side of [`Afterscript`]
+#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Hash, Eq)]
+pub enum UserAfterscript {
```
Comment (mgazeel) [inline src/gourd_lib/config/mod.rs:79]: I actually think this makes the afterscript system more complex.

Why do we need all of these variants? The way there were handled before seemed much simpler.
Whilst I agree with some of the other changes this new struct should not be here.

File: src/gourd_lib/config/mod.rs [hunk 3]
```diff
@@ -380,18 +398,51 @@ impl Config {
...
+impl UserAfterscript {
+    /// Canonicalize the path to the afterscript executable.
+    pub fn canonicalize(&self, fs: &impl FileOperations) -> Result<Afterscript> {
+        let initial = match self {
+            Self::Complex(Afterscript { executable }) => executable,
+            Self::Simple(executable) => executable,
+        };
+        let executable = canon_path(initial, fs)?;
+        // on unix, check the file permissions and ensure the afterscript is executable.
+        #[cfg(unix)]
```
Comment (mgazeel) [inline src/gourd_lib/config/mod.rs:416]: No! Permissions can chage.

You should check when executing it, not when preparing the experiment.
The name of this function "`canonicalize`" is also very deceiving, it does so much more than canonicalize.

**Review by mgazeel — CHANGES_REQUESTED** [review]

File: src/gourd/post/afterscript.rs [hunk 4]
```diff
@@ -1,113 +1,70 @@
...
-                    .ok_or(anyhow!("Status does not exist"))
-                    .with_context(ctx!(
-                        "Could not get the exit code of the execution", ;
-                        "",
-                    ))? ; "", ; "", );
-    }
+    let afterscript_result = String::from_utf8_lossy(&afterscript_output.stdout)
+        .trim()
+        .to_string();
+    debug!("stdout: {afterscript_result}");
```
Comment (mgazeel) [inline src/gourd/post/afterscript.rs:36]: This debug statement is unhelpful.

Try: `afterscript: ..., said: ...`

File: src/gourd_lib/config/mod.rs (hunk 2 above)
Comment (andtsa) [reply src/gourd_lib/config/mod.rs:79]: the goal here is to allow for more options in after scripts, such as specifying whether input should be passed as a file path or contents and through arguments vs stdin, maybe users explicitly want the creation of a file for example. while none of these options are implemented, in the current system we would either have them as fields in `program` which is even worse imo, or require users to specify a struct-like declaration of every afterscript. this allows for both
```
afterscript = "/path/to/script.sh"
```
and 
```
afterscript = { executable = "/path/to/script.sh", option_a = "something", option_b = true }
```
to be valid. I found this to be most friendly to new users who shouldn't be required to understand the options, and let more experienced users customise the afterscript execution however they want.

Do you believe 
a) afterscripts should be kept dead simple and any customisation is unnecessary complication that we shouldn't support anyway
b) there should be a different solution for supporting both one-line and multiple option declaration
c) we should have the complex declaration for all after scripts 
d) something else?

File: src/gourd_lib/config/mod.rs (hunk 3 above)
Comment (andtsa) [reply src/gourd_lib/config/mod.rs:416]: permissions can change indeed, but is there really a scenario when they will *have* change between the experiment creation and status execution? because as a user I would rather when the experiment starts that there's no more debugging needed!

as for the name, agreed, will change.

File: src/gourd/post/afterscript.rs (hunk 4 above)
Comment (andtsa) [reply src/gourd/post/afterscript.rs:36]: agreed! will fix

File: src/gourd/wrapper/mod.rs (hunk 1 above)
Comment (andtsa) [reply src/gourd/wrapper/mod.rs:54]: - it causes no errors on other systems 
- I personally want to use `~` in my file paths, plus the error when you use a `~` is misleading 
- I imagine it would let people that know what they're doing do quite a lot with environment variable expansion

I would be willing to remove the variable expansion, but personally I quite enjoy being able to use user home in my paths. if you want to remove that, id want to be convinced it's a problem.

File: src/gourd_lib/config/mod.rs (hunk 2 above)
Comment (mgazeel) [reply src/gourd_lib/config/mod.rs:79]: a) yes
b) no
c) no
d) the users are already writing a custom `.sh` script that gourd executes, there is no need for these options as the language the shell provides can do anything, I'd focus on providing concrete examples on how to do something with an after script that are easily accessible with `gourd init` for example instead of adding new options.

File: src/gourd/post/afterscript.rs (hunk 4 above)
Comment (mgazeel) [reply src/gourd/post/afterscript.rs:36]: Thanks!

File: src/gourd_lib/config/mod.rs (hunk 2 above)
Comment (andtsa) [reply src/gourd_lib/config/mod.rs:79]: My original idea was to cater for externally provided scripts, without needing the user to modify them. To be honest I'm giving up on the idea and instead providing examples for how to deal with an external script needing the input provided differently. Simple it is!

File: src/gourd/wrapper/mod.rs (hunk 1 above)
Comment (andtsa) [reply src/gourd/wrapper/mod.rs:54]: 1. It doesn't do anything on windows.
2. That's a great argument for removing variable expansion, but not for home dir expansion (~). Do you have any reasoning for removing that one too?

File: src/gourd_lib/config/mod.rs (hunk 3 above)
Comment (andtsa) [reply src/gourd_lib/config/mod.rs:416]: Your first point I agree with, and thus a check before execution is prudent, but the last point is personal preference. Why should the user care when afterscripts get executed?

File: src/gourd/wrapper/mod.rs (hunk 1 above)
Comment (mgazeel) [reply src/gourd/wrapper/mod.rs:54]: 2. I do not if you can do it without shell expand or a slimmer dependency.

Comment (andtsa) [reply src/gourd/wrapper/mod.rs]: With feature flags the shellexpand dependency now just contains a few traits and a single function, namely `shellexpand::tilde()` which will prevent confusing home dir errors. We could copy the function into our codebase but I feel that would be an unnecessary pollution. what do you think?

File: src/gourd/cli/process.rs [hunk 5]
```diff
@@ -199,29 +205,53 @@ pub async fn process_command(cmd: &Cli) -> Result<()> {
...
+            // then get the statuses
             let statuses = experiment.status(&file_system)?;
 
             match run_id {
                 Some(id) => {
-                    display_job(&mut stdout(), &experiment, &statuses, *id)?;
+                    // only print the afterscript output,
+                    // in a script-readable format (nothing fancy)
+                    if *after_out {
+                        if let Some(out) = &experiment.runs[*id].afterscript_output {
```
Comment (andtsa) [inline src/gourd/cli/process.rs:223]: id isn't yet sanitised, this could cause a panic. Use .get.map so that case is caught generically by the else

File: src/gourd/post/labels.rs [hunk 6]
```diff
@@ -1,41 +1,33 @@
...
-    debug!("Assigning label to {:?}", source_file);
+    debug!("Assigning label for text {:?}", source_text);
 
     let mut result_label: Option<String> = None;
 
-    let text = fs.read_utf8(source_file)?;
-    let label_map = &experiment.labels.map;
+    let label_map = &experiment.labels;
     let mut keys = label_map.keys().collect::<Vec<&String>>();
     keys.sort_unstable_by(|a, b| label_map[*b].priority.cmp(&label_map[*a].priority));
```
Comment (andtsa) [inline src/gourd/post/labels.rs:19]: This might be able to change to sort_unstable_by_key

File: src/gourd/status/printing.rs [hunk 7]
```diff
@@ -526,17 +530,52 @@ pub fn display_job(
...
+                let truncate_output = |x: &mut String| {
+                    let mut touch = false;
+                    if x.len() > TRUNCATE_AFTERSCRIPT_OUTPUT.0 {
+                        touch = true;
+                        x.truncate(TRUNCATE_AFTERSCRIPT_OUTPUT.0);
+                    }
+                    if x.lines().count() > TRUNCATE_AFTERSCRIPT_OUTPUT.1 {
+                        *x = x.lines().take(TRUNCATE_AFTERSCRIPT_OUTPUT.1).collect();
+                        touch = true;
+                    }
```
Comment (andtsa) [inline src/gourd/status/printing.rs:548]: I don't know if I actually tested this, could be prudent to make sure it works. It's also possible to remove the if entirely
